/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aoapps_io_posix_PosixFile_SecuredDirectory */

#ifndef _Included_com_aoapps_io_posix_PosixFile_SecuredDirectory
#define _Included_com_aoapps_io_posix_PosixFile_SecuredDirectory
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
