/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aoindustries_io_unix_UnixFile */

#ifndef _Included_com_aoindustries_io_unix_UnixFile
#define _Included_com_aoindustries_io_unix_UnixFile
#ifdef __cplusplus
extern "C" {
#endif
#undef com_aoindustries_io_unix_UnixFile_MINIMUM_USER_UID
#define com_aoindustries_io_unix_UnixFile_MINIMUM_USER_UID 500L
#undef com_aoindustries_io_unix_UnixFile_MINIMUM_USER_GID
#define com_aoindustries_io_unix_UnixFile_MINIMUM_USER_GID 500L
#undef com_aoindustries_io_unix_UnixFile_ROOT_UID
#define com_aoindustries_io_unix_UnixFile_ROOT_UID 0L
#undef com_aoindustries_io_unix_UnixFile_ROOT_GID
#define com_aoindustries_io_unix_UnixFile_ROOT_GID 0L
#undef com_aoindustries_io_unix_UnixFile_PERMISSION_MASK
#define com_aoindustries_io_unix_UnixFile_PERMISSION_MASK 4095LL
#undef com_aoindustries_io_unix_UnixFile_OTHER_EXECUTE
#define com_aoindustries_io_unix_UnixFile_OTHER_EXECUTE 1LL
#undef com_aoindustries_io_unix_UnixFile_NOT_OTHER_EXECUTE
#define com_aoindustries_io_unix_UnixFile_NOT_OTHER_EXECUTE -2LL
#undef com_aoindustries_io_unix_UnixFile_OTHER_WRITE
#define com_aoindustries_io_unix_UnixFile_OTHER_WRITE 2LL
#undef com_aoindustries_io_unix_UnixFile_NOT_OTHER_WRITE
#define com_aoindustries_io_unix_UnixFile_NOT_OTHER_WRITE -3LL
#undef com_aoindustries_io_unix_UnixFile_OTHER_READ
#define com_aoindustries_io_unix_UnixFile_OTHER_READ 4LL
#undef com_aoindustries_io_unix_UnixFile_NOT_OTHER_READ
#define com_aoindustries_io_unix_UnixFile_NOT_OTHER_READ -5LL
#undef com_aoindustries_io_unix_UnixFile_GROUP_EXECUTE
#define com_aoindustries_io_unix_UnixFile_GROUP_EXECUTE 8LL
#undef com_aoindustries_io_unix_UnixFile_NOT_GROUP_EXECUTE
#define com_aoindustries_io_unix_UnixFile_NOT_GROUP_EXECUTE -9LL
#undef com_aoindustries_io_unix_UnixFile_GROUP_WRITE
#define com_aoindustries_io_unix_UnixFile_GROUP_WRITE 16LL
#undef com_aoindustries_io_unix_UnixFile_NOT_GROUP_WRITE
#define com_aoindustries_io_unix_UnixFile_NOT_GROUP_WRITE -17LL
#undef com_aoindustries_io_unix_UnixFile_GROUP_READ
#define com_aoindustries_io_unix_UnixFile_GROUP_READ 32LL
#undef com_aoindustries_io_unix_UnixFile_NOT_GROUP_READ
#define com_aoindustries_io_unix_UnixFile_NOT_GROUP_READ -33LL
#undef com_aoindustries_io_unix_UnixFile_USER_EXECUTE
#define com_aoindustries_io_unix_UnixFile_USER_EXECUTE 64LL
#undef com_aoindustries_io_unix_UnixFile_NOT_USER_EXECUTE
#define com_aoindustries_io_unix_UnixFile_NOT_USER_EXECUTE -65LL
#undef com_aoindustries_io_unix_UnixFile_USER_WRITE
#define com_aoindustries_io_unix_UnixFile_USER_WRITE 128LL
#undef com_aoindustries_io_unix_UnixFile_NOT_USER_WRITE
#define com_aoindustries_io_unix_UnixFile_NOT_USER_WRITE -129LL
#undef com_aoindustries_io_unix_UnixFile_USER_READ
#define com_aoindustries_io_unix_UnixFile_USER_READ 256LL
#undef com_aoindustries_io_unix_UnixFile_NOT_USER_READ
#define com_aoindustries_io_unix_UnixFile_NOT_USER_READ -257LL
#undef com_aoindustries_io_unix_UnixFile_SAVE_TEXT_IMAGE
#define com_aoindustries_io_unix_UnixFile_SAVE_TEXT_IMAGE 512LL
#undef com_aoindustries_io_unix_UnixFile_NOT_SAVE_TEXT_IMAGE
#define com_aoindustries_io_unix_UnixFile_NOT_SAVE_TEXT_IMAGE -513LL
#undef com_aoindustries_io_unix_UnixFile_SET_GID
#define com_aoindustries_io_unix_UnixFile_SET_GID 1024LL
#undef com_aoindustries_io_unix_UnixFile_NOT_SET_GID
#define com_aoindustries_io_unix_UnixFile_NOT_SET_GID -1025LL
#undef com_aoindustries_io_unix_UnixFile_SET_UID
#define com_aoindustries_io_unix_UnixFile_SET_UID 2048LL
#undef com_aoindustries_io_unix_UnixFile_NOT_SET_UID
#define com_aoindustries_io_unix_UnixFile_NOT_SET_UID -2049LL
#undef com_aoindustries_io_unix_UnixFile_TYPE_MASK
#define com_aoindustries_io_unix_UnixFile_TYPE_MASK 61440LL
#undef com_aoindustries_io_unix_UnixFile_IS_FIFO
#define com_aoindustries_io_unix_UnixFile_IS_FIFO 4096LL
#undef com_aoindustries_io_unix_UnixFile_IS_CHARACTER_DEVICE
#define com_aoindustries_io_unix_UnixFile_IS_CHARACTER_DEVICE 8192LL
#undef com_aoindustries_io_unix_UnixFile_IS_DIRECTORY
#define com_aoindustries_io_unix_UnixFile_IS_DIRECTORY 16384LL
#undef com_aoindustries_io_unix_UnixFile_IS_BLOCK_DEVICE
#define com_aoindustries_io_unix_UnixFile_IS_BLOCK_DEVICE 24576LL
#undef com_aoindustries_io_unix_UnixFile_IS_REGULAR_FILE
#define com_aoindustries_io_unix_UnixFile_IS_REGULAR_FILE 32768LL
#undef com_aoindustries_io_unix_UnixFile_IS_SYM_LINK
#define com_aoindustries_io_unix_UnixFile_IS_SYM_LINK 40960LL
#undef com_aoindustries_io_unix_UnixFile_IS_SOCKET
#define com_aoindustries_io_unix_UnixFile_IS_SOCKET 49152LL
/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    chown0
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_aoindustries_io_unix_UnixFile_chown0
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    getStat0
 * Signature: (Ljava/lang/String;Lcom/aoindustries/io/unix/Stat;)V
 */
JNIEXPORT void JNICALL Java_com_aoindustries_io_unix_UnixFile_getStat0
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    crypt0
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aoindustries_io_unix_UnixFile_crypt0
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    mktemp0
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aoindustries_io_unix_UnixFile_mktemp0
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    mknod0
 * Signature: (Ljava/lang/String;JJ)V
 */
JNIEXPORT void JNICALL Java_com_aoindustries_io_unix_UnixFile_mknod0
  (JNIEnv *, jclass, jstring, jlong, jlong);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    mkfifo0
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_aoindustries_io_unix_UnixFile_mkfifo0
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    setMode0
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_aoindustries_io_unix_UnixFile_setMode0
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    symLink0
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aoindustries_io_unix_UnixFile_symLink0
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    link0
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aoindustries_io_unix_UnixFile_link0
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    readLink0
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aoindustries_io_unix_UnixFile_readLink0
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_aoindustries_io_unix_UnixFile
 * Method:    utime0
 * Signature: (Ljava/lang/String;JJ)V
 */
JNIEXPORT void JNICALL Java_com_aoindustries_io_unix_UnixFile_utime0
  (JNIEnv *, jclass, jstring, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
