/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aoapps_io_posix_linux_DevRandom */

#ifndef _Included_com_aoapps_io_posix_linux_DevRandom
#define _Included_com_aoapps_io_posix_linux_DevRandom
#ifdef __cplusplus
extern "C" {
#endif
#undef com_aoapps_io_posix_linux_DevRandom_serialVersionUID
#define com_aoapps_io_posix_linux_DevRandom_serialVersionUID 3905348978240129619LL
#undef com_aoapps_io_posix_linux_DevRandom_multiplier
#define com_aoapps_io_posix_linux_DevRandom_multiplier 25214903917LL
#undef com_aoapps_io_posix_linux_DevRandom_addend
#define com_aoapps_io_posix_linux_DevRandom_addend 11LL
#undef com_aoapps_io_posix_linux_DevRandom_mask
#define com_aoapps_io_posix_linux_DevRandom_mask 281474976710655LL
#undef com_aoapps_io_posix_linux_DevRandom_DOUBLE_UNIT
#define com_aoapps_io_posix_linux_DevRandom_DOUBLE_UNIT 1.1102230246251565E-16
#undef com_aoapps_io_posix_linux_DevRandom_serialVersionUID
#define com_aoapps_io_posix_linux_DevRandom_serialVersionUID 4190090095484650210LL
/*
 * Class:     com_aoapps_io_posix_linux_DevRandom
 * Method:    addEntropy0
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_aoapps_io_posix_linux_DevRandom_addEntropy0
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
